import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import profilePic from "../../public/images/profile/me.png";
import profilePic from "../../public/images/profile/developer-pic-4.png";
import Layout from "@/components/Layout";
import AnimatedText from "@/components/AnimatedText";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import useThemeSwitcher from "@/components/hooks/useThemeSwitcher";

export default function Home() {
  const [mode, setMode] = useThemeSwitcher();

  return (
    <>
      <Head>
        <title>Phoebe Su' s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />

      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="Profile pic"
                className="w-full h-auto transform -scale-x-100 animate-fade lg:hidden md:inline-block md:w-full"
                priority
                sizes="(max-width:768px) 100vw, (max-width:1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Welcome to my Portfolio. I'm Phoebe Su✨"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5 sm:!text-3xl"
              />
              <AnimatedText
                className="my-4 text-left text-base font-medium md:text-sm sm:text-xs lg:text-center"
                text="A knack for problem-solving and a positive, creative mindset. I
                gain immense satisfaction from crafting solutions and seeing
                tangible impacts for people."
              />
              <div
                className="flex items-center self-start mt-2 lg:self-center
              "
              >
                <Link
                  href="/Phoebe Su CV.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-sold border-transparent hover:border-dark transition dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base "
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:phoebesu85@yahoo.com.tw"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBulb}
            alt=""
            className={`w-full h-auto cursor-pointer opacity-30 brightness-75 dark:opacity-100 dark:brightness-150	`}
            onClick={() => setMode(mode === "light" ? "dark" : "light")}
          />
        </div>
      </main>
    </>
  );
}
